/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReadingRouteImport } from './routes/reading'
import { Route as PronunciationRouteImport } from './routes/pronunciation'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlacementRouteImport } from './routes/placement'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MediaRouteImport } from './routes/media'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as CefrLevelsRouteImport } from './routes/cefr-levels'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiCoachRouteImport } from './routes/ai-coach'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WatchVideoIdRouteImport } from './routes/watch.$videoId'
import { Route as VerifyCodeRouteImport } from './routes/verify.$code'
import { Route as LevelExamLevelRouteImport } from './routes/level-exam.$level'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'
import { Route as CheckoutPlanIdRouteImport } from './routes/checkout.$planId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminCurriculumRouteImport } from './routes/admin/curriculum'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingRoute = ReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => rootRouteImport,
} as any)
const PronunciationRoute = PronunciationRouteImport.update({
  id: '/pronunciation',
  path: '/pronunciation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementRoute = PlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const CefrLevelsRoute = CefrLevelsRouteImport.update({
  id: '/cefr-levels',
  path: '/cefr-levels',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCoachRoute = AiCoachRouteImport.update({
  id: '/ai-coach',
  path: '/ai-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WatchVideoIdRoute = WatchVideoIdRouteImport.update({
  id: '/watch/$videoId',
  path: '/watch/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCodeRoute = VerifyCodeRouteImport.update({
  id: '/verify/$code',
  path: '/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelExamLevelRoute = LevelExamLevelRouteImport.update({
  id: '/level-exam/$level',
  path: '/level-exam/$level',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPlanIdRoute = CheckoutPlanIdRouteImport.update({
  id: '/checkout/$planId',
  path: '/checkout/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCurriculumRoute = AdminCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-coach': typeof AiCoachRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/cefr-levels': typeof CefrLevelsRoute
  '/certificates': typeof CertificatesRoute
  '/classes': typeof ClassesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/curriculum': typeof CurriculumRoute
  '/dashboard': typeof DashboardRoute
  '/games': typeof GamesRoute
  '/maintenance': typeof MaintenanceRoute
  '/media': typeof MediaRoute
  '/onboarding': typeof OnboardingRoute
  '/placement': typeof PlacementRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/pronunciation': typeof PronunciationRoute
  '/reading': typeof ReadingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscription': typeof SubscriptionRoute
  '/track': typeof TrackRoute
  '/videos': typeof VideosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/curriculum': typeof AdminCurriculumRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/level-exam/$level': typeof LevelExamLevelRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-coach': typeof AiCoachRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/cefr-levels': typeof CefrLevelsRoute
  '/certificates': typeof CertificatesRoute
  '/classes': typeof ClassesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/curriculum': typeof CurriculumRoute
  '/dashboard': typeof DashboardRoute
  '/games': typeof GamesRoute
  '/maintenance': typeof MaintenanceRoute
  '/media': typeof MediaRoute
  '/onboarding': typeof OnboardingRoute
  '/placement': typeof PlacementRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/pronunciation': typeof PronunciationRoute
  '/reading': typeof ReadingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscription': typeof SubscriptionRoute
  '/track': typeof TrackRoute
  '/videos': typeof VideosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/curriculum': typeof AdminCurriculumRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/level-exam/$level': typeof LevelExamLevelRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-coach': typeof AiCoachRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/cefr-levels': typeof CefrLevelsRoute
  '/certificates': typeof CertificatesRoute
  '/classes': typeof ClassesRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/curriculum': typeof CurriculumRoute
  '/dashboard': typeof DashboardRoute
  '/games': typeof GamesRoute
  '/maintenance': typeof MaintenanceRoute
  '/media': typeof MediaRoute
  '/onboarding': typeof OnboardingRoute
  '/placement': typeof PlacementRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/pronunciation': typeof PronunciationRoute
  '/reading': typeof ReadingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscription': typeof SubscriptionRoute
  '/track': typeof TrackRoute
  '/videos': typeof VideosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/curriculum': typeof AdminCurriculumRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/level-exam/$level': typeof LevelExamLevelRoute
  '/verify/$code': typeof VerifyCodeRoute
  '/watch/$videoId': typeof WatchVideoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-coach'
    | '/analytics'
    | '/audit'
    | '/auth'
    | '/cefr-levels'
    | '/certificates'
    | '/classes'
    | '/community'
    | '/contact'
    | '/curriculum'
    | '/dashboard'
    | '/games'
    | '/maintenance'
    | '/media'
    | '/onboarding'
    | '/placement'
    | '/pricing'
    | '/profile'
    | '/pronunciation'
    | '/reading'
    | '/reset-password'
    | '/rewards'
    | '/settings'
    | '/sitemap.xml'
    | '/subscription'
    | '/track'
    | '/videos'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/curriculum'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/checkout/$planId'
    | '/lesson/$lessonId'
    | '/level-exam/$level'
    | '/verify/$code'
    | '/watch/$videoId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-coach'
    | '/analytics'
    | '/audit'
    | '/auth'
    | '/cefr-levels'
    | '/certificates'
    | '/classes'
    | '/community'
    | '/contact'
    | '/curriculum'
    | '/dashboard'
    | '/games'
    | '/maintenance'
    | '/media'
    | '/onboarding'
    | '/placement'
    | '/pricing'
    | '/profile'
    | '/pronunciation'
    | '/reading'
    | '/reset-password'
    | '/rewards'
    | '/settings'
    | '/sitemap.xml'
    | '/subscription'
    | '/track'
    | '/videos'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/curriculum'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/checkout/$planId'
    | '/lesson/$lessonId'
    | '/level-exam/$level'
    | '/verify/$code'
    | '/watch/$videoId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ai-coach'
    | '/analytics'
    | '/audit'
    | '/auth'
    | '/cefr-levels'
    | '/certificates'
    | '/classes'
    | '/community'
    | '/contact'
    | '/curriculum'
    | '/dashboard'
    | '/games'
    | '/maintenance'
    | '/media'
    | '/onboarding'
    | '/placement'
    | '/pricing'
    | '/profile'
    | '/pronunciation'
    | '/reading'
    | '/reset-password'
    | '/rewards'
    | '/settings'
    | '/sitemap.xml'
    | '/subscription'
    | '/track'
    | '/videos'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/curriculum'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/checkout/$planId'
    | '/lesson/$lessonId'
    | '/level-exam/$level'
    | '/verify/$code'
    | '/watch/$videoId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiCoachRoute: typeof AiCoachRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  CefrLevelsRoute: typeof CefrLevelsRoute
  CertificatesRoute: typeof CertificatesRoute
  ClassesRoute: typeof ClassesRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  CurriculumRoute: typeof CurriculumRoute
  DashboardRoute: typeof DashboardRoute
  GamesRoute: typeof GamesRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MediaRoute: typeof MediaRoute
  OnboardingRoute: typeof OnboardingRoute
  PlacementRoute: typeof PlacementRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  PronunciationRoute: typeof PronunciationRoute
  ReadingRoute: typeof ReadingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RewardsRoute: typeof RewardsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TrackRoute: typeof TrackRoute
  VideosRoute: typeof VideosRoute
  CheckoutPlanIdRoute: typeof CheckoutPlanIdRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
  LevelExamLevelRoute: typeof LevelExamLevelRoute
  VerifyCodeRoute: typeof VerifyCodeRoute
  WatchVideoIdRoute: typeof WatchVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading': {
      id: '/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof ReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronunciation': {
      id: '/pronunciation'
      path: '/pronunciation'
      fullPath: '/pronunciation'
      preLoaderRoute: typeof PronunciationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement': {
      id: '/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cefr-levels': {
      id: '/cefr-levels'
      path: '/cefr-levels'
      fullPath: '/cefr-levels'
      preLoaderRoute: typeof CefrLevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-coach': {
      id: '/ai-coach'
      path: '/ai-coach'
      fullPath: '/ai-coach'
      preLoaderRoute: typeof AiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/watch/$videoId': {
      id: '/watch/$videoId'
      path: '/watch/$videoId'
      fullPath: '/watch/$videoId'
      preLoaderRoute: typeof WatchVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$code': {
      id: '/verify/$code'
      path: '/verify/$code'
      fullPath: '/verify/$code'
      preLoaderRoute: typeof VerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level-exam/$level': {
      id: '/level-exam/$level'
      path: '/level-exam/$level'
      fullPath: '/level-exam/$level'
      preLoaderRoute: typeof LevelExamLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$planId': {
      id: '/checkout/$planId'
      path: '/checkout/$planId'
      fullPath: '/checkout/$planId'
      preLoaderRoute: typeof CheckoutPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/curriculum': {
      id: '/admin/curriculum'
      path: '/curriculum'
      fullPath: '/admin/curriculum'
      preLoaderRoute: typeof AdminCurriculumRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCurriculumRoute: typeof AdminCurriculumRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCurriculumRoute: AdminCurriculumRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AiCoachRoute: AiCoachRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  CefrLevelsRoute: CefrLevelsRoute,
  CertificatesRoute: CertificatesRoute,
  ClassesRoute: ClassesRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  CurriculumRoute: CurriculumRoute,
  DashboardRoute: DashboardRoute,
  GamesRoute: GamesRoute,
  MaintenanceRoute: MaintenanceRoute,
  MediaRoute: MediaRoute,
  OnboardingRoute: OnboardingRoute,
  PlacementRoute: PlacementRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  PronunciationRoute: PronunciationRoute,
  ReadingRoute: ReadingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RewardsRoute: RewardsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubscriptionRoute: SubscriptionRoute,
  TrackRoute: TrackRoute,
  VideosRoute: VideosRoute,
  CheckoutPlanIdRoute: CheckoutPlanIdRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
  LevelExamLevelRoute: LevelExamLevelRoute,
  VerifyCodeRoute: VerifyCodeRoute,
  WatchVideoIdRoute: WatchVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
